wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TY/TYEMQ/Algorithm-Diff-1.1902.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JS/JSMITH/Algorithm-Merge-0.08.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/H/HI/HISSO/Alien-SeleniumRC-1.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AB/ABW/AppConfig-1.66.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BI/BINGOS/Archive-Tar-1.76.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Archive-Zip-1.30.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/B-Compiling-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/B-Hooks-EndOfScope-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/B-Hooks-OP-Check-0.18.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/B-Hooks-OP-PPAddr-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/B-Keywords-1.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/ST/STBEY/Bit-Vector-7.1.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOWMANBS/CGI-Expand-2.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANDYA/CGI-Simple-1.113.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANDK/CPAN-1.9600.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/CPAN-Meta-2.110580.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/CPAN-Meta-YAML-0.003.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/Z/ZO/ZOFFIX/POE-Component-IRC-Plugin-CSS-Minifier-0.0101.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CL/CLEISHMAN/Cache-2.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JS/JSWARTZ/Cache-Cache-1.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RO/ROBM/Cache-FastMmap-1.36.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DORMANDO/Cache-Memcached-1.29.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/K/KR/KROKI/Cache-Memcached-Fast-0.19.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/E/EL/ELIZABETH/Cache-Memcached-Managed-0.20.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/Capture-Tiny-0.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSCHWERN/Carp-Assert-0.20.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PETDANCE/Carp-Assert-More-1.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/ST/STBEY/Carp-Clan-6.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANDREMAR/Catalyst-Action-RenderView-ErrorHandler-0.100162.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Authentication-Credential-HTTP-1.013.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Catalyst-Devel-1.33.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-Authentication-0.10017.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JG/JGOULAH/Catalyst-Plugin-AutoRestart-0.93.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-Cache-0.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GR/GRAF/Catalyst-Plugin-Cache-HTTP-0.001000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BR/BRICAS/Catalyst-Plugin-ConfigLoader-0.30.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHISEL/Catalyst-Plugin-ErrorCatcher-0.0.8.8.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-I18N-0.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-Session-0.31.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSTROUT/Catalyst-Plugin-Session-State-Cookie-0.17.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SS/SSCAFFIDI/Catalyst-Plugin-Session-Store-FastMmap-0.14.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Catalyst-Plugin-Session-Store-File-0.18.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Catalyst-Plugin-Session-Store-Memcached-0.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSTROUT/Catalyst-Plugin-StackTrace-0.11.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSTROUT/Catalyst-Plugin-Static-Simple-0.29.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Plugin-Unicode-Encoding-1.1.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Catalyst-Runtime-5.80032.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AB/ABRAXXA/Catalyst-View-TT-0.36.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/K/KW/KWMAK/Chart/Gnuplot/Chart-Gnuplot-0.15.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RU/RUZ/Class-Accessor-Fast-XS-0.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Class-C3-Adopt-NEXT-0.13.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CL/CLACO/Class-Data-Accessor-0.04004.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TM/TMTM/Class-Data-Inheritable-0.08.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Class-Factory-Util-1.7.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Class-Inspector-1.25.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SA/SARTAK/Class-Load-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Class-MOP-1.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AB/ABW/Class-Singleton-1.4.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PM/PMQS/Compress-Raw-Bzip2-2.033.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PM/PMQS/Compress-Raw-Zlib-2.033.tar.gz
wget -c http://backpan.perl.org/authors/id/B/BR/BRICAS/Config-Any-0.20.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TL/TLINDEN/Config-General-2.50.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Config-Tiny-2.14.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SM/SMUELLER/PathTools-3.33.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TU/TURNSTEP/DBD-Pg-2.18.0.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/DBD-SQLite-1.31.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TI/TIMB/DBI-1.616.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DC/DCANTRELL/Data-Compare-1.22.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AP/APLA/Data-Dump-XML-1.19.tar.gz
wget -c http://backpan.perl.org/authors/id/S/SM/SMUELLER/Data-Dumper-2.128.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FR/FREW/Data-Dumper-Concise-2.020.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/L/LB/LBROCARD/Data-Page-2.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Data-Visitor-0.27.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/ST/STBEY/Date-Calc-6.3.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/DateTime-0.66.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.80.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SC/SCHUBIGER/DateTime-Format-Natural-0.96.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DM/DMAKI/DateTime-Format-Pg-0.16005.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.5000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GW/GWILLIAMS/DateTime-Format-W3CDTF-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/DateTime-Locale-0.45.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/DateTime-TimeZone-1.31.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RC/RCLAMP/Devel-Caller-2.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/L/LD/LDS/Devel-Cycle-1.11.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Devel-Declare-0.006001.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Devel-StackTrace-1.27.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DM/DMUEY/Digest-MD5-File-0.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSHELOR/Digest-SHA-5.61.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DOY/Dist-CheckConflicts-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-Abstract-3.004.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-Address-1.892.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-MIME-1.907.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-MIME-ContentType-1.015.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-MIME-Encodings-1.313.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-MessageID-1.402.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-Sender-0.110000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-Simple-2.100.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Email-Valid-0.184.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JG/JGMYERS/Encode-Detect-1.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DS/DSB/Env-Path-0.18.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Exception-Base-0.2401.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Exception-Class-1.32.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Exception-Died-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Exception-Warning-0.0401.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/ExtUtils-CBuilder-0.280202.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/ExtUtils-Depends-0.304.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSCHWERN/ExtUtils-MakeMaker-6.56.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/ExtUtils-ParseXS-2.2206.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/FCGI-0.71.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GB/GBJK/FCGI-ProcManager-0.19.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Fatal-Exception-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/File-ChangeNotify-0.19.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RC/RCLAMP/File-Find-Rule-0.32.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/File-Find-Rule-Perl-1.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/File-HomeDir-0.97.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BB/BBB/File-NFSLock-1.20.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/File-Remove-1.49.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/File-ShareDir-1.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GW/GWYN/File-ShareDir-Install-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/U/UR/URI/File-Slurp-9999.15.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/File-Which-1.09.tar.gz
wget -c http://backpan.perl.org/authors/id/M/MA/MAUKE/Function-Parameters-0.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.089.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BJ/BJOERN/HTML-Encoding-0.61.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GS/GSHANK/HTML-FormHandler-0.33002.tar.gz
wget -c http://backpan.perl.org/authors/id/T/TO/TOBYINK/HTML-HTML5-Parser-0.103.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TO/TOBYINK/HTML-HTML5-Sanity-0.101.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANDYA/HTML-Tiny-1.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MI/MIROD/HTML-TreeBuilder-XPath-0.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GE/GETTY/HTTP-Body-1.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MATTIASH/HTTP-Cache-Transparent-1.0.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/HTTP-Request-AsCGI-1.2.tar.gz
wget -c http://backpan.perl.org/authors/id/J/JE/JESSE/HTTP-Server-Simple-0.43.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/N/NU/NUFFIN/Hash-Util-FieldHash-Compat-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JM/JMM/Heap-0.80.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHORNY/Hook-LexWrap-0.24.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/I/IN/INGY/IO-All-0.41.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TO/TOMHUGHES/IO-Zlib-1.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/IPC-Run3-0.044.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MAKAMAKA/JSON-2.51.tar.gz
wget -c http://backpan.perl.org/authors/id/P/PE/PERIGRIN/JSON-Any-1.26.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MAKAMAKA/JSON-PP-2.27105.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/ML/MLEHMANN/JSON-XS-2.32.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SH/SHIRIRU/Javascript-Closure-0.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MM/MMORGAN/LWP-UserAgent-Mockable-1.10.tgz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/List-AllUtils-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GB/GBARR/Scalar-List-Utils-1.23_02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PEVANS/List-UtilsBy-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DRTECH/Locale-Maketext-Lexicon-0.86.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JE/JESSE/Locale-Maketext-Simple-0.21.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/K/KE/KEN/Locale-PO-0.21.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Log-Dispatch-2.29.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.32.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/MIME-Lite-3.027.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MARKOV/MIME-Types-1.31.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AL/ALLENDAY/Math-Combinatorics-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RH/RHESA/Method-Signatures-Simple-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/Module-Build-0.3800.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BI/BINGOS/Module-CoreList-2.46.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AS/ASH/Module-Install-ProvidesClass-1.000000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BI/BINGOS/Module-Load-Conditional-0.44.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/Module-Metadata-1.000004.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RS/RSCHUPP/Module-ScanDeps-1.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Module-Signature-0.66.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MATTLAW/Module-Util-1.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Moose-1.24.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DOY/MooseX-ABC-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/N/NU/NUFFIN/MooseX-Clone-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/MooseX-Emulate-Class-Accessor-Fast-0.00903.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/MooseX-Getopt-0.37.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/MooseX-MethodAttributes-0.24.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/MooseX-Params-Validate-0.16.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SA/SARTAK/MooseX-Role-Parameterized-0.25.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/MooseX-Role-WithOverloading-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JR/JROCKWAY/MooseX-Runnable-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/MooseX-SemiAffordanceAccessor-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/MooseX-Singleton-0.26.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/MooseX-Types-0.25.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GR/GRODITI/MooseX-Types-Common-0.001002.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/N/NU/NUFFIN/MooseX-Types-DateTime-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TH/THEPLER/MooseX-Types-Path-Class-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JJ/JJNAPIORK/MooseX-Types-Structured-0.26.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/MooseX-Types-URI-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/N/NA/NATON/Net-Amazon-AWSSign-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CW/CWEST/Net-SMTP-SSL-1.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PR/PROFERO/Number-Compare-Date-0.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Object-Signature-1.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SM/SMUELLER/PAR-Dist-0.47.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/PPI-1.215.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/W/WY/WYANT/PPIx-Regexp-0.019.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/E/EL/ELLIOTJS/PPIx-Utilities-1.001000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Package-DeprecationManager-0.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DOY/Package-Stash-0.28.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DOY/Package-Stash-XS-0.22.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RO/ROBIN/PadWalker-1.92.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/Params-Validate-0.95.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/Parse-CPAN-Meta-1.4401.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DC/DCONWAY/Parse-RecDescent-1.965001.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/K/KW/KWILLIAMS/Path-Class-0.23.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/E/EL/ELLIOTJS/Perl-Critic-1.114.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Perl-MinimumVersion-1.28.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DAGOLDEN/Perl-OSType-1.002.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SH/SHANCOCK/Perl-Tidy-20101217.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SB/SBURKE/Pod-Spell-1.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/K/KW/KWILLIAMS/Probe-Perl-0.01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DU/DURIST/Proc-ProcessTable-0.45.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GW/GWILLIAMS/RDF-Query-2.905.tar.gz
wget -c http://backpan.perl.org/authors/id/T/TO/TOBYINK/RDF-RDFa-Parser-1.094.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GW/GWILLIAMS/RDF-Trine-0.134_01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RO/ROODE/Readonly-XS-1.03.tar.gz
wget -c http://backpan.perl.org/authors/id/V/VP/VPIT/Scope-Upper-0.14.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SA/SAMV/Set-Object-1.28.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JH/JHI/Set-Scalar-1.25.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AM/AMS/Storable-2.25.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SO/SOENKE/String-CRC32-1.4.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/H/HI/HIO/String-CamelCase-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/E/EV/EVO/String-Escape-2010.002.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DA/DARREN/String-Format-1.16.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/String-RewritePrefix-0.006.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RO/ROSCH/String-ShellQuote-1.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/String-TT-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Sub-Exporter-0.982.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/O/OV/OVID/Sub-Override-0.08.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Symbol-Util-0.0202.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AB/ABW/Template-Toolkit-2.22.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RC/RCLAMP/Template-Plugin-Class-0.14.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PETDANCE/Template-Timer-1.00.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/Test-Aggregate-0.364.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Test-Assert-0.0504.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Test-Deep-0.108.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/O/OV/OVID/Test-Differences-0.500.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADIE/Test-Exception-0.31.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Test-Fatal-0.003.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANDYA/Test-Harness-3.23.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/O/OV/OVID/Test-JSON-0.11.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RG/RGARCIA/Test-LongString-0.15.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CY/CYCLES/Test-Magpie-0.05.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PETDANCE/Test-Memory-Cycle-1.04.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Test-MinimumVersion-0.101080.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Test-Mock-Class-0.0303.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/L/LU/LUKEC/Test-Mock-LWP-0.05.tar.gz
wget -c http://backpan.perl.org/authors/id/C/CH/CHROMATIC/Test-MockObject-1.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DD/DDICK/Test-MockTime-0.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/O/OV/OVID/Test-Most-0.23.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Test-NoWarnings-1.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Test-Object-0.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PETDANCE/Test-Pod-Coverage-1.08.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TO/TOKUHIROM/Test-Requires-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Test-Routine-0.009.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Test-Script-1.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSCHWERN/Test-Simple-0.98_01.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Test-SubCalls-1.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JR/JROCKWAY/Test-TableDriven-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FD/FDALY/Test-Tester-0.107.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/Test-Unit-Lite-0.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PETDANCE/Test-WWW-Mechanize-1.30.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BO/BOBTFISH/Test-WWW-Mechanize-Catalyst-0.53.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/L/LU/LUKEC/Test-WWW-Selenium-1.24.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AS/ASH/Test-WWW-Selenium-Catalyst-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHORNY/Test-Warn-0.23.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AU/AUDREYT/Test-use-ok-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANNO/Text-Aligner-0.07.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MAKAMAKA/Text-CSV-1.21.tar.gz
wget -c http://backpan.perl.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-0.85.tgz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/Text-Diff-1.37.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RC/RCLAMP/Text-Glob-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MR/MRAMBERG/Text-SimpleTable-2.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AN/ANNO/Text-Table-1.116.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MA/MATTLAW/Text-Trim-1.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/L/LD/LDACHARY/Text-Unaccent-1.08.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHROMATIC/Text-WikiFormat-0.79.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Throwable-0.102080.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/N/NU/NUFFIN/Tie-ToObject-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AV/AVIF/Time-Duration-1.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CO/COGENT/Tree-DAG_Node-1.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/ST/STEVAN/Tree-Simple-1.18.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/ST/STEVAN/Tree-Simple-VisitorFactory-0.10.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DO/DOY/Try-Tiny-0.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AS/ASH/TryCatch-1.003000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHROMATIC/UNIVERSAL-can-1.16.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/C/CH/CHROMATIC/UNIVERSAL-isa-1.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GA/GAAS/URI-1.58.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DR/DROLSKY/URI-FromHash-0.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/I/IT/ITWARRIOR/Unicode-Escape-0.0.2.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GA/GAAS/Unicode-String-2.09.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/R/RJ/RJBS/Version-Requirements-0.101020.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PERIGRIN/XML-CommonNS-0.06.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/B/BH/BHOLZMAN/XML-Generator-1.03.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/T/TO/TOBYINK/XML-LibXML-Debugging-0.100.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AB/ABW/XML-Namespace-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/P/PE/PERIGRIN/XML-NamespaceFactory-1.00.tar.gz
wget -c http://backpan.perl.org/authors/id/T/TJ/TJMATHER/XML-RegExp-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/S/SH/SHLOMIF/XML-SemanticDiff-1.0000.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/G/GR/GRANTM/XML-Simple-2.18.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MS/MSERGEANT/XML-XPath-1.13.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/MI/MIROD/XML-XPathEngine-0.12.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/YAML-0.72.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/A/AD/ADAMK/YAML-Tiny-1.48.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/I/IN/INGY/boolean-0.26.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/M/ML/MLEHMANN/common-sense-3.4.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/D/DE/DEXTER/constant-boolean-0.02.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/F/FL/FLORA/namespace-clean-0.20.tar.gz
wget -c ftp://download.xs4all.nl/pub/mirror/CPAN/authors/id/J/JP/JPEACOCK/version-0.88.tar.gz
