#!/bin/bash
set +e
cpanm --notest URI-1.58.tar.gz
cpanm --notest XML-Generator-1.03.tar.gz
cpanm --notest Test-Harness-3.23.tar.gz
cpanm --notest Email-Address-1.892.tar.gz
cpanm --notest Perl-OSType-1.002.tar.gz
cpanm --notest Alien-SeleniumRC-1.03.tar.gz
cpanm --notest Math-Combinatorics-0.09.tar.gz
cpanm --notest DBI-1.616.tar.gz
cpanm --notest Cache-Memcached-Fast-0.19.tar.gz
cpanm --notest XML-RegExp-0.02.tar.gz
cpanm --notest Unicode-String-2.09.tar.gz
cpanm --notest Locale-Maketext-Simple-0.21.tar.gz
cpanm --notest PadWalker-1.92.tar.gz
cpanm --notest Email-MIME-ContentType-1.015.tar.gz
cpanm --notest Set-Object-1.28.tar.gz
cpanm --notest Test-LongString-0.15.tar.gz
cpanm --notest HTTP-Server-Simple-0.43.tar.gz
cpanm --notest Config-Any-0.20.tar.gz
cpanm --notest boolean-0.26.tar.gz
cpanm --notest UNIVERSAL-isa-1.03.tar.gz
cpanm --notest Email-Valid-0.184.tar.gz
cpanm --notest Data-Dumper-Concise-2.020.tar.gz
cpanm --notest Set-Scalar-1.25.tar.gz
cpanm --notest Test-Pod-Coverage-1.08.tar.gz
cpanm --notest Digest-MD5-File-0.07.tar.gz
cpanm --notest Text-SimpleTable-2.03.tar.gz
cpanm --notest Compress-Raw-Zlib-2.033.tar.gz
cpanm --notest Symbol-Util-0.0202.tar.gz
cpanm --notest YAML-0.72.tar.gz
cpanm --notest Test-TableDriven-0.02.tar.gz
cpanm --notest Perl-Tidy-20101217.tar.gz
cpanm --notest Devel-Cycle-1.11.tar.gz
cpanm --notest Test-use-ok-0.02.tar.gz
cpanm --notest Test-Tester-0.107.tar.gz
cpanm --notest Scope-Upper-0.14.tar.gz
cpanm --notest IPC-Run3-0.044.tar.gz
cpanm --notest POE-Component-IRC-Plugin-CSS-Minifier-0.0101.tar.gz
cpanm --notest XML-XPath-1.13.tar.gz
cpanm --notest File-NFSLock-1.20.tar.gz
cpanm --notest ANSIColor-3.00.tar.gz
cpanm --notest Test-Unit-Lite-0.12.tar.gz
cpanm --notest XML-Simple-2.18.tar.gz
cpanm --notest FCGI-0.71.tar.gz
cpanm --notest JSON-Any-1.26.tar.gz
cpanm --notest String-CRC32-1.4.tar.gz
cpanm --notest Class-Factory-Util-1.7.tar.gz
cpanm --notest FCGI-ProcManager-0.19.tar.gz
cpanm --notest Data-Dump-XML-1.19.tar.gz
cpanm --notest Config-Tiny-2.14.tar.gz
cpanm --notest Storable-2.25.tar.gz
cpanm --notest IO-All-0.41.tar.gz
cpanm --notest Locale-Maketext-Lexicon-0.86.tar.gz
cpanm --notest Scalar-List-Utils-1.23_02.tar.gz
cpanm --notest Module-CoreList-2.46.tar.gz
cpanm --notest HTML-Tiny-1.05.tar.gz
cpanm --notest Class-Singleton-1.4.tar.gz
cpanm --notest Carp-Assert-0.20.tar.gz
cpanm --notest Compress-Raw-Bzip2-2.033.tar.gz
cpanm --notest Text-Aligner-0.07.tar.gz
cpanm --notest Text-Trim-1.02.tar.gz
cpanm --notest Module-Util-1.07.tar.gz
cpanm --notest JSON-2.51.tar.gz
cpanm --notest Try-Tiny-0.09.tar.gz
cpanm --notest B-Keywords-1.10.tar.gz
cpanm --notest Javascript-Closure-0.07.tar.gz
cpanm --notest Digest-SHA-5.61.tar.gz
cpanm --notest Readonly-XS-1.03.tar.gz
cpanm --notest File-Slurp-9999.15.tar.gz
cpanm --notest Class-Data-Accessor-0.04004.tar.gz
cpanm --notest String-Format-1.16.tar.gz
cpanm --notest Heap-0.80.tar.gz
cpanm --notest XML-Namespace-0.02.tar.gz
cpanm --notest Test-Requires-0.06.tar.gz
cpanm --notest common-sense-3.4.tar.gz
cpanm --notest Sub-Exporter-0.982.tar.gz
cpanm --notest JSON-PP-2.27105.tar.gz
cpanm --notest PathTools-3.33.tar.gz
cpanm --notest Algorithm-Diff-1.1902.tar.gz
cpanm --notest MIME-Types-1.31.tar.gz
cpanm --notest Env-Path-0.18.tar.gz
cpanm --notest Pod-Spell-1.01.tar.gz
cpanm --notest Email-MIME-Encodings-1.313.tar.gz
cpanm --notest String-ShellQuote-1.04.tar.gz
cpanm --notest Text-Unaccent-1.08.tar.gz
cpanm --notest version-0.88.tar.gz
cpanm --notest XML-XPathEngine-0.12.tar.gz
cpanm --notest IO-Zlib-1.10.tar.gz
cpanm --notest HTTP-Cache-Transparent-1.0.tar.gz
cpanm --notest Class-Data-Inheritable-0.08.tar.gz
cpanm --notest Email-Simple-2.100.tar.gz
cpanm --notest Probe-Perl-0.01.tar.gz
cpanm --notest Module-Signature-0.66.tar.gz
cpanm --notest Class-Accessor-Fast-XS-0.04.tar.gz
cpanm --notest Data-Dumper-2.128.tar.gz
cpanm --notest Test-MockTime-0.12.tar.gz
cpanm --notest AppConfig-1.66.tar.gz
cpanm --notest String-Escape-2010.002.tar.gz
cpanm --notest HTML-Encoding-0.61.tar.gz
cpanm --notest XML-NamespaceFactory-1.00.tar.gz
cpanm --notest Hook-LexWrap-0.24.tar.gz
cpanm --notest Number-Compare-Date-0.01.tar.gz
cpanm --notest Tree-DAG_Node-1.06.tar.gz
cpanm --notest Net-SMTP-SSL-1.01.tar.gz
cpanm --notest String-CamelCase-0.02.tar.gz
cpanm --notest DBD-Pg-2.18.0.tar.gz
cpanm --notest Time-Duration-1.06.tar.gz
cpanm --notest ExtUtils-CBuilder-0.280202.tar.gz
cpanm --notest B-Hooks-EndOfScope-0.09.tar.gz
cpanm --notest Capture-Tiny-0.10.tar.gz
cpanm --notest Module-Metadata-1.000004.tar.gz
cpanm --notest ExtUtils-Depends-0.304.tar.gz
cpanm --notest Text-Table-1.116.tar.gz
cpanm --notest String-RewritePrefix-0.006.tar.gz
cpanm --notest Test-Script-1.07.tar.gz
cpanm --notest CPAN-Meta-YAML-0.003.tar.gz
cpanm --notest B-Compiling-0.02.tar.gz
cpanm --notest Devel-StackTrace-1.27.tar.gz
cpanm --notest Version-Requirements-0.101020.tar.gz
cpanm --notest HTML-HTML5-Parser-0.103.tar.gz
cpanm --notest Log-Log4perl-1.32.tar.gz
cpanm --notest Hash-Util-FieldHash-Compat-0.03.tar.gz
cpanm --notest Test-NoWarnings-1.02.tar.gz
cpanm --notest Cache-Cache-1.06.tar.gz
cpanm --notest XML-LibXML-Debugging-0.100.tar.gz
cpanm --notest Net-Amazon-AWSSign-0.09.tar.gz
cpanm --notest Email-MessageID-1.402.tar.gz
cpanm --notest Email-Abstract-3.004.tar.gz
cpanm --notest Cache-2.04.tar.gz
cpanm --notest Archive-Tar-1.76.tar.gz
cpanm --notest Text-WikiFormat-0.79.tar.gz
cpanm --notest Template-Toolkit-2.22.tar.gz
cpanm --notest Text-CSV-1.21.tar.gz
cpanm --notest Exception-Base-0.2401.tar.gz
cpanm --notest XML-CommonNS-0.06.tar.gz
cpanm --notest YAML-Tiny-1.48.tar.gz
cpanm --notest Devel-Caller-2.05.tar.gz
cpanm --notest PAR-Dist-0.47.tar.gz
cpanm --notest Parse-RecDescent-1.965001.tar.gz
cpanm --notest ExtUtils-MakeMaker-6.56.tar.gz
cpanm --notest Test-Fatal-0.003.tar.gz
cpanm --notest Chart-Gnuplot-0.15.tar.gz
cpanm --notest Cache-Memcached-1.29.tar.gz
cpanm --notest Class-Inspector-1.25.tar.gz
cpanm --notest Tie-ToObject-0.03.tar.gz
cpanm --notest Text-Diff-1.37.tar.gz
cpanm --notest Proc-ProcessTable-0.45.tar.gz
cpanm --notest JSON-XS-2.32.tar.gz
cpanm --notest Test-SubCalls-1.09.tar.gz
cpanm --notest Test-Object-0.07.tar.gz
cpanm --notest HTTP-Request-AsCGI-1.2.tar.gz
cpanm --notest Cache-FastMmap-1.36.tar.gz
cpanm --notest Unicode-Escape-0.0.2.tar.gz
cpanm --notest constant-boolean-0.02.tar.gz
cpanm --notest DBD-SQLite-1.31.tar.gz
cpanm --notest HTML-TreeBuilder-XPath-0.12.tar.gz
cpanm --notest Test-Warn-0.23.tar.gz
cpanm --notest File-Remove-1.49.tar.gz
cpanm --notest Test-Simple-0.98_01.tar.gz
cpanm --notest MIME-Lite-3.027.tar.gz
cpanm --notest Archive-Zip-1.30.tar.gz
cpanm --notest Config-General-2.50.tar.gz
cpanm --notest Locale-PO-0.21.tar.gz
cpanm --notest Path-Class-0.23.tar.gz
cpanm --notest Test-Memory-Cycle-1.04.tar.gz
cpanm --notest Algorithm-Merge-0.08.tar.gz
cpanm --notest Module-Load-Conditional-0.44.tar.gz
cpanm --notest Object-Signature-1.07.tar.gz
cpanm --notest File-ShareDir-Install-0.03.tar.gz
cpanm --notest B-Hooks-OP-Check-0.18.tar.gz
cpanm --notest Package-Stash-XS-0.22.tar.gz
cpanm --notest Class-Load-0.06.tar.gz
cpanm --notest Test-Assert-0.0504.tar.gz
cpanm --notest Parse-CPAN-Meta-1.4401.tar.gz
cpanm --notest Template-Plugin-Class-0.14.tar.gz
cpanm --notest HTML-HTML5-Sanity-0.101.tar.gz
cpanm --notest ExtUtils-ParseXS-2.2206.tar.gz
cpanm --notest Package-DeprecationManager-0.10.tar.gz
cpanm --notest Exception-Class-1.32.tar.gz
cpanm --notest B-Hooks-OP-PPAddr-0.03.tar.gz
cpanm --notest Template-Timer-1.00.tar.gz
cpanm --notest File-ShareDir-1.03.tar.gz
cpanm --notest Dist-CheckConflicts-0.02.tar.gz
cpanm --notest PPI-1.215.tar.gz
cpanm --notest Cache-Memcached-Managed-0.20.tar.gz
cpanm --notest Email-MIME-1.907.tar.gz
cpanm --notest File-Which-1.09.tar.gz
cpanm --notest Test-Deep-0.108.tar.gz
cpanm --notest Exception-Died-0.06.tar.gz
cpanm --notest Package-Stash-0.28.tar.gz
cpanm --notest Moose-1.24.tar.gz
cpanm --notest File-HomeDir-0.97.tar.gz
cpanm --notest PPIx-Regexp-0.019.tar.gz
cpanm --notest Devel-Declare-0.006001.tar.gz
cpanm --notest Exception-Warning-0.0401.tar.gz
cpanm --notest RDF-RDFa-Parser-1.094.tar.gz
cpanm --notest HTTP-Body-1.12.tar.gz
cpanm --notest CPAN-Meta-2.110580.tar.gz
cpanm --notest Function-Parameters-0.04.tar.gz
cpanm --notest Module-Build-0.3800.tar.gz
cpanm --notest MooseX-SemiAffordanceAccessor-0.09.tar.gz
cpanm --notest MooseX-Singleton-0.26.tar.gz
cpanm --notest Fatal-Exception-0.05.tar.gz
cpanm --notest Throwable-0.102080.tar.gz
cpanm --notest Method-Signatures-Simple-0.06.tar.gz
cpanm --notest MooseX-Role-Parameterized-0.25.tar.gz
cpanm --notest namespace-clean-0.20.tar.gz
cpanm --notest Encode-Detect-1.01.tar.gz
cpanm --notest Test-Routine-0.009.tar.gz
cpanm --notest Test-Differences-0.500.tar.gz
cpanm --notest PPIx-Utilities-1.001000.tar.gz
cpanm --notest CGI-Simple-1.113.tar.gz
cpanm --notest Data-Visitor-0.27.tar.gz
cpanm --notest List-UtilsBy-0.06.tar.gz
cpanm --notest Params-Validate-0.95.tar.gz
cpanm --notest Test-Mock-Class-0.0303.tar.gz
cpanm --notest UNIVERSAL-can-1.16.tar.gz
cpanm --notest XML-SemanticDiff-1.0000.tar.gz
cpanm --notest Text-Glob-0.09.tar.gz
cpanm --notest Module-ScanDeps-1.01.tar.gz
cpanm --notest Test-Exception-0.31.tar.gz
cpanm --notest List-AllUtils-0.02.tar.gz
cpanm --notest Sub-Override-0.08.tar.gz
cpanm --notest Tree-Simple-1.18.tar.gz
cpanm --notest Test-MockObject-1.09.tar.gz
cpanm --notest DateTime-Locale-0.45.tar.gz
cpanm --notest Class-C3-Adopt-NEXT-0.13.tar.gz
cpanm --notest Log-Dispatch-2.29.tar.gz
cpanm --notest Test-JSON-0.11.tar.gz
cpanm --notest MooseX-Emulate-Class-Accessor-Fast-0.00903.tar.gz
cpanm --notest CGI-Expand-2.03.tar.gz
cpanm --notest Getopt-Long-Descriptive-0.089.tar.gz
cpanm --notest CPAN-1.9600.tar.gz
cpanm --notest Module-Install-ProvidesClass-1.000000.tar.gz
cpanm --notest Carp-Clan-6.04.tar.gz
cpanm --notest File-Find-Rule-0.32.tar.gz
cpanm --notest String-TT-0.03.tar.gz
cpanm --notest MooseX-Params-Validate-0.16.tar.gz
cpanm --notest URI-FromHash-0.03.tar.gz
cpanm --notest MooseX-Clone-0.05.tar.gz
cpanm --notest Perl-Critic-1.114.tar.gz
cpanm --notest Data-Page-2.02.tar.gz
cpanm --notest DateTime-TimeZone-1.31.tar.gz
cpanm --notest MooseX-ABC-0.05.tar.gz
cpanm --notest Test-Most-0.23.tar.gz
cpanm --notest Carp-Assert-More-1.12.tar.gz
cpanm --notest Data-Compare-1.22.tar.gz
cpanm --notest Test-WWW-Mechanize-1.30.tar.gz
cpanm --notest File-Find-Rule-Perl-1.10.tar.gz
cpanm --notest Bit-Vector-7.1.tar.gz
cpanm --notest DateTime-0.66.tar.gz
cpanm --notest Test-Mock-LWP-0.05.tar.gz
cpanm --notest File-ChangeNotify-0.19.tar.gz
cpanm --notest Test-Aggregate-0.364.tar.gz
cpanm --notest MooseX-Types-0.25.tar.gz
cpanm --notest RDF-Trine-0.134_01.tar.gz
cpanm --notest MooseX-Getopt-0.37.tar.gz
cpanm --notest Tree-Simple-VisitorFactory-0.10.tar.gz
cpanm --notest MooseX-Types-Common-0.001002.tar.gz
cpanm --notest DateTime-Format-Natural-0.96.tar.gz
cpanm --notest TryCatch-1.003000.tar.gz
cpanm --notest MooseX-Types-DateTime-0.05.tar.gz
cpanm --notest MooseX-Role-WithOverloading-0.09.tar.gz
cpanm --notest Date-Calc-6.3.tar.gz
cpanm --notest DateTime-Format-W3CDTF-0.06.tar.gz
cpanm --notest MooseX-Types-Path-Class-0.05.tar.gz
cpanm --notest MooseX-MethodAttributes-0.24.tar.gz
cpanm --notest Test-WWW-Selenium-1.24.tar.gz
cpanm --notest DateTime-Format-Strptime-1.5000.tar.gz
cpanm --notest Perl-MinimumVersion-1.28.tar.gz
cpanm --notest HTML-FormHandler-0.33002.tar.gz
cpanm --notest Test-MinimumVersion-0.101080.tar.gz
cpanm --notest Catalyst-Runtime-5.80032.tar.gz
cpanm --notest DateTime-Format-Builder-0.80.tar.gz
cpanm --notest MooseX-Types-Structured-0.26.tar.gz
cpanm --notest MooseX-Runnable-0.03.tar.gz
cpanm --notest RDF-Query-2.905.tar.gz
cpanm --notest MooseX-Types-URI-0.02.tar.gz
cpanm --notest Catalyst-Plugin-I18N-0.10.tar.gz
cpanm --notest Test-Magpie-0.05.tar.gz
cpanm --notest Catalyst-Plugin-Session-0.31.tar.gz
cpanm --notest Catalyst-Plugin-Unicode-Encoding-1.1.tar.gz
cpanm --notest Catalyst-Plugin-ConfigLoader-0.30.tar.gz
cpanm --notest Catalyst-Plugin-Cache-0.10.tar.gz
cpanm --notest Catalyst-Plugin-AutoRestart-0.93.tar.gz
cpanm --notest Test-WWW-Selenium-Catalyst-0.06.tar.gz
cpanm --notest DateTime-Format-Pg-0.16005.tar.gz
cpanm --notest Catalyst-View-TT-0.36.tar.gz
cpanm --notest Catalyst-Plugin-Static-Simple-0.29.tar.gz
cpanm --notest Catalyst-Plugin-StackTrace-0.11.tar.gz
cpanm --notest Email-Sender-0.110000.tar.gz
cpanm --notest Catalyst-Action-RenderView-ErrorHandler-0.100162.tar.gz
cpanm --notest Catalyst-Devel-1.33.tar.gz
cpanm --notest Catalyst-Plugin-Session-Store-File-0.18.tar.gz
cpanm --notest Catalyst-Plugin-Session-Store-FastMmap-0.14.tar.gz
cpanm --notest Catalyst-Plugin-Authentication-0.10017.tar.gz
cpanm --notest Catalyst-Plugin-Session-State-Cookie-0.17.tar.gz
cpanm --notest Catalyst-Plugin-Session-Store-Memcached-0.04.tar.gz
cpanm --notest Catalyst-Authentication-Credential-HTTP-1.013.tar.gz
cpanm --notest Test-WWW-Mechanize-Catalyst-0.53.tar.gz
cpanm --notest Catalyst-Plugin-ErrorCatcher-0.0.8.8.tar.gz
cpanm --notest Catalyst-Plugin-Cache-HTTP-0.001000.tar.gz
